[window]
dimensions={ columns = 50, lines = 20}
padding = { x = 10, y = 5}
#opacity = 0.67
#blur = false 
title = "Intern Wizard"
startup_mode = "Windowed"#"Windowed" # Maximized | Fullscreen
class = { instance = "Alacritty", general = "Alacrity" }
decorations = "none"
decorations_theme_variant = "none"#"Light" #"Dark"  # | Light
[scrolling]
history = 10000 # Default 10000
multiplier = 5 # Default= 3
[font]
normal = { family = "JetBrainsMono Nerd font", style = "Regular"}
#normal = {family = "Sans"}
size = 10 
offset= { x = 1, y = 8}

[general]
import = [
    "~/.config/alacritty/themes/moonlight_ii_vscode.toml"
]

[colors]
# Dùng bright-colors cho bold text
draw_bold_text_with_bright_colors = true



#[terminal]
#shell = {program = "wsl.exe", args = ["~"]}

# shell = "zellij"
# debug otions are meant to help troubleshoot issues with Alacritty
# These can change or be removed entirely without warning
# So their stability shouldn't be relied upon
[debug]
render_timer=false
highlight_damage = false # | if u want to hit yourself, you can select true
