[window]
dimensions={ columns = 50, lines = 100}
padding = { x = 10, y = 10}
opacity = 0.92
blur = true
title = "Alacritty customize"
startup_mode = "Windowed"#"Windowed" # Maximized | Fullscreen
class = { instance = "Alacritty", general = "Alacrity" }
decorations = "none"
decorations_theme_variant = "none"#"Light" #"Dark"  # | Light
[scrolling]
history = 10000 # Default 10000
multiplier = 5 # Default= 3
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 11
offset= { x = 1, y = 4}
[general]
import = [
    "./themes/pastelnight.toml"
]
[debug]
render_timer=false
highlight_damage = false 
